In [5]:
import numpy as np

# 1: How to Find the Index of Maximum and Minimum Values in a NumPy Array?

In [6]:
arr = np.array([10, 25, 2, 67, 89, 45])
max = np.amax(arr)
min =np.amin(arr)
print(max)
print(min)

89
2


# 2: How to Replace All Values Greater than a Threshold with a Specific Value?
Replace all values greater than 10 with 99

In [7]:
arr = np.array([3, 10, 18, 21, 5, 9])
arr[arr>10]=99
print(arr)

[ 3 10 99 99  5  9]


# 3:⁠ ⁠How to Find Unique Elements and Their Counts in an Array?

In [8]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
a = np.unique_counts(arr)

# 4: ⁠How to Perform Row-Wise and Column-Wise Operations in NumPy?
you can do: sum of all rows and sum of all columns

In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a=np.sum(matrix,axis=1)
b=np.sum(matrix,axis=0)
print(a)
print(b)

[ 6 15 24]
[12 15 18]


# 5:⁠ ⁠How to Generate a Random Matrix and Normalize It?


In [10]:
rand_matrix = np.random.rand(3,3)
rand_matrix_mean = np.mean(rand_matrix,axis=1)
rand_matrix_std=np.std(rand_matrix,axis=1)
normalize_matrix = (rand_matrix -rand_matrix_mean )/rand_matrix_std
print(normalize_matrix)
normalized_matrix = (rand_matrix - np.min(rand_matrix)) / (np.max(rand_matrix) - np.min(rand_matrix))
print(normalized_matrix)


[[ 0.15640405 -0.7400754   0.87251418]
 [-2.27382575  0.70284879  0.55188864]
 [ 1.68640833 -0.25646971 -0.58626066]]
[[0.61365812 0.24705406 0.86178127]
 [0.         0.77585484 0.77897264]
 [1.         0.42428517 0.48502043]]


# 6:⁠ ⁠How to Find the Euclidean Distance Between Two Vectors?

In [11]:
v1 = np.array([3, 4, 5])
v2 = np.array([1, 1, 1])

In [12]:
distance = np.sqrt(np.sum((v1 - v2) ** 2))
print(distance)

5.385164807134504


In [13]:
distance = np.linalg.norm(v1 - v2)
print(distance)

5.385164807134504


# 7:⁠ ⁠How to Shuffle Rows of a NumPy Array?

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.random.shuffle(arr)
print(arr)

[[4 5 6]
 [7 8 9]
 [1 2 3]]


# 8: How to Find the Dot Product and Cross Product of Two Vectors?

In [15]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

a = np.dot(v1,v2)
b = np.cross(v1,v2)

print(a)
print(b)


32
[-3  6 -3]
