In [1]:
import numpy as np

# 1. Add a 1D array [10, 20, 30] to each row of a 2D array. #2d([[1, 2, 3], [4, 5, 6]])
a = np.array([10, 20, 30])
b = np.array([[1, 2, 3], [4, 5, 6]])

# 2. Multiply a column vector with a row vector using broadcasting:

X= np.array([[1], [2], [3]]) # Shape (3,1)

Y = np.array([10, 20, 30]) # Shape (1,3)

# 3. Subtract a row vector from each row of a 2D matrix:

A = np.array([[5, 10, 15], [20, 25, 30]]) # Shape (2,3)

B = np.array([1, 2, 3]) # Shape (3,)

# 4. Compute the mean of a 2D array and subtract it from each row.

A = np.array([[10, 20, 30], [40, 58, 60], [70, 80, 90]])

# 5. Fix the broadcasting error by reshaping the array.

A = np.array([[1, 2], [3, 4]])

B = np.array([10, 20])

# 6. Multiply each row of a matrix by a different scalar.

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

scalars =  np.array([1, 2, 3])

# 7. Normalize a 2D array (subtract mean and divide by std deviation).

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Os

# 1

In [ ]:
#add oneD array to each row of 2Darray
a = np.array([10, 20, 30])
b = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
a+b

array([[11, 22, 33],
       [14, 25, 36]])

# 2

In [6]:
X= np.array([[1], [2], [3]]) # Shape (3,1)

Y = np.array([10, 20, 30]) # Shape (1,3)

In [8]:
X*Y

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

# 3

In [9]:
A = np.array([[5, 10, 15], [20, 25, 30]]) # Shape (2,3)

B  = np.array([1, 2, 3]) # Shape (3,)

In [10]:
A-B

array([[ 4,  8, 12],
       [19, 23, 27]])

# 4

In [11]:
A = np.array([[10, 20, 30], [40, 58, 60], [70, 80, 90]])

In [17]:
B = np.mean(A)

In [18]:
A-B

array([[-40.88888889, -30.88888889, -20.88888889],
       [-10.88888889,   7.11111111,   9.11111111],
       [ 19.11111111,  29.11111111,  39.11111111]])

# 5


In [19]:
A = np.array([[1, 2], [3, 4]])

B = np.array([10, 20])

In [20]:
A+B

array([[11, 22],
       [13, 24]])

# 6

In [21]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

scalars =  np.array([1, 2, 3])


In [22]:
A * scalars

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

# 7


In [24]:
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])


mean_A = np.mean(A)
std_A = np.std(A)


normalized_A = (A - mean_A) / std_A

print(normalized_A)


[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
