In [3]:
import numpy as np


In [4]:
a = np.array([[1,2],[2,3]])
a.shape

(2, 2)

In [5]:
b = np.array([10,20,30])
b.shape

(3,)

In [6]:
b = np.array([10,20,30])

In [7]:
# a+b

In [8]:
b.reshape(3,1)

array([[10],
       [20],
       [30]])

In [9]:
a = np.array([[1,2],[2,3],[3,4]])
a.shape

(3, 2)

In [10]:
b = np.array([10,20,30]).reshape(3,1)

In [11]:
a+b

array([[11, 12],
       [22, 23],
       [33, 34]])

#tiling method

In [13]:
a = np.array([[1,2],[2,3]])
a.shape

(2, 2)

In [14]:
b = np.array([10,20,30])
b.shape



(3,)

In [29]:
b_tiled = np.tile(b[:2],(2,1))

In [30]:
b_tiled

array([[10, 20],
       [10, 20]])

In [31]:
a+b_tiled

array([[11, 22],
       [12, 23]])