# **1Darray**

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
b = np.array(45)   #this is 0D array

In [5]:
type(b)

numpy.ndarray

In [6]:
b.ndim #to check dimension of array

0

In [7]:
a[1:4] #slicing the array

array([2, 3, 4])

In [8]:
a[::-1][2:] #printing reverse array

array([3, 2, 1])

In [9]:
a[::2] #skipping the values

array([1, 3, 5])

In [10]:
##two d array

# **2Darray**

In [11]:
arr = np.array([[1,2,3],[4,5,6]])

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr[0,1:3]#access the 2d array

array([2, 3])

In [16]:
print(arr[:,1:].flatten()) # flattening the array and accessing the last twon rows

[2 3 5 6]


In [17]:
print(arr[:,1].ravel()) #different method for flattening

[2 5]


# **3D array**

In [18]:
arr = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])




In [19]:
arr.ndim

3

In [20]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [21]:
arr.shape

(2, 2, 3)

operation on array


In [22]:
np.sin(arr)

array([[[ 0.84147098,  0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427, -0.2794155 ]],

       [[ 0.6569866 ,  0.98935825,  0.41211849],
        [-0.54402111, -0.99999021, -0.53657292]]])

In [34]:
arr.max()

np.int64(12)

In [33]:
arr.min()

np.int64(1)

In [26]:
np.exp(arr)

array([[[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02]],

       [[1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
        [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]])

In [27]:
np.sqrt(arr)

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[2.64575131, 2.82842712, 3.        ],
        [3.16227766, 3.31662479, 3.46410162]]])

In [28]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [29]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [30]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.split(arr1,3)

[array([1]), array([2]), array([3])]

In [52]:
ar = np.random.randint(5)

In [53]:
ar

2

In [ ]:
ar1 = np.random.rand(3,7)

In [48]:
ar1

array([[0.80119374, 0.59908934, 0.79187024, 0.10530947, 0.00898496,
        0.87757027, 0.04872415],
       [0.52541408, 0.47554647, 0.05839306, 0.10493612, 0.13367086,
        0.33393777, 0.59123941],
       [0.20318681, 0.19155872, 0.91161301, 0.39661423, 0.2566007 ,
        0.74173353, 0.26126726]])

In [56]:
ar2 = np.random.randint(5,100,(6,6))

In [57]:
ar2

array([[19, 52, 65, 20, 62, 96],
       [34, 40, 81, 54, 18, 75],
       [92, 88, 87, 55, 33, 95],
       [98, 49, 45, 10,  6, 41],
       [20, 53, 16, 14, 26, 26],
       [25, 99, 71, 15, 57, 37]])

In [58]:
ar1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [60]:
ar2 = np.random.randint(1,100,(4,4))
ar2

array([[26, 24, 56, 59],
       [94, 93, 45, 46],
       [88, 47,  9, 66],
       [56,  3,  6, 76]])

In [ ]:


arr = np.array([10,15,20,25,30,35,40])
even_numbers = arr[arr % 2 == 0]
print(even_numbers)

[10 20 30 40]


In [ ]:


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[arr % 2 != 0] = -1 
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [66]:
arr  = np.array([1,2,3,4,5,6,7,8,9])
a = arr.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
ar1 = np.array([1,2,3,4,5,6,7,8,9])

In [74]:
print(np.min(ar1))

1


In [75]:
print(np.max(ar1))

9


In [77]:
arr = np.eye(4, dtype=int)
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [82]:
arr = np.zeros(4 ,dtype=int)
arr

array([0, 0, 0, 0])

In [84]:
arr = np.ones(4 ,dtype=int)
arr

array([1, 1, 1, 1])

In [87]:
arr = np.diag([4,5,6,7,8,9])
arr

array([[4, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0],
       [0, 0, 6, 0, 0, 0],
       [0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 9]])

In [90]:
arr = np.linspace(1,20,10)
arr

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [91]:
arr = np.eye(5, dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [99]:
ar1 = np.array([10,9,8,7,6,5,4,3,2,1])
ar1.sort()
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [103]:
print(ar1.sum())

55


In [104]:
arr = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])


arr[:, [0, 2]] = arr[:, [2, 0]]

print(arr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


# Generate a 5x5 matrix where each row contains values from 1 to 5.
# Find the most frequently occurring element in an array.
# Given an array, replace all values greater than 10 with 10:
arr = np.array([5, 15, 25, 10, 8, 3, 12])
# Find the sum of each row in a 384 matrix:
arr = np.array ( [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] )
# Find the index of the maximum element in the array.
arr = np.array([10, 20, 5, 30, 25])
# Find the mean, median, and standard deviation of:
arr - np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Swap column 0 and column 2 in the given 3%3 matrix.
### arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) **bold text**
# Find unique values and their counts in:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 510])