In [1]:
pip install numpy


  Using cached numpy-2.2.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.2.3-cp313-cp313-win_amd64.whl (12.6 MB)


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
list =[1,2,3,4,5]
list[-5:-2]
# list[:]

[1, 2, 3]

In [3]:
list[-3::-1]

[3, 2, 1]

In [4]:
list[::2]

[1, 3, 5]

In [5]:
import numpy as np

In [6]:
arr =np.array([1,2,3,4,5])

In [7]:
print(arr[1:])

[2 3 4 5]


In [8]:
arr1 =np.array([[1,2,3],[4,5,6]])

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
type(arr1)

numpy.ndarray

In [11]:
arr1.ndim

2

In [12]:
arr1[0,0]

np.int64(1)

In [13]:
print(arr1[0,1:3])

[2 3]


In [14]:
print(arr1[:,1:])

[[2 3]
 [5 6]]


In [15]:
print(arr1[:,1:].flatten())

[2 3 5 6]


In [16]:
print(arr1[:,1:].ravel())

[2 3 5 6]


In [17]:
arr = np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,10]]])

In [18]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 5,  6,  7],
        [ 8,  9, 10]]])

In [19]:
arr.ndim

3

In [20]:
print(arr.shape)

(2, 2, 3)


In [21]:
print(arr[1:2,0])

[[5 6 7]]


In [22]:
np.sin(arr)

array([[[ 0.84147098,  0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427, -0.2794155 ]],

       [[-0.95892427, -0.2794155 ,  0.6569866 ],
        [ 0.98935825,  0.41211849, -0.54402111]]])

In [23]:
np.min(arr)

np.int64(1)

In [24]:
np.max(arr)

np.int64(10)

In [25]:
np.sqrt(arr)

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[2.23606798, 2.44948974, 2.64575131],
        [2.82842712, 3.        , 3.16227766]]])

In [26]:
arr =np.array([1,2,3,4,5])

In [27]:
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [28]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [29]:
arr=np.random.randint(8)

In [30]:
arr

1

In [31]:
arr3=np.random.rand(3,3)

In [32]:
arr3

array([[0.08261312, 0.75402422, 0.87189773],
       [0.4565864 , 0.13175203, 0.20766585],
       [0.36860717, 0.16447329, 0.81669148]])

In [33]:
ar=np.random.randint(1,100,5)

In [34]:
ar

array([43, 26, 75, 35, 98], dtype=int32)

In [35]:
ar=np.random.randint(1,50,(3,3))

In [36]:
ar

array([[42, 20, 38],
       [36, 36, 36],
       [36, 17, 42]], dtype=int32)

In [37]:
# 1, create a 1D array of number from 1 to 10
ar=np.array([1,2,3,4,5,6,7,8,9,10])
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
ar=np.random.randint(1,100,(3))
ar

array([68, 32, 20], dtype=int32)

In [39]:
# 1. Create a 10 array of numbers from 1 to 10.

#2.Generate a 4x4 matrix of random integers between 1 and 10

#3. Extract all even numbers from the array:

#arr = np.array([10, 15, 20, 25, 30, 35, 40])

#4. Replace all odd numbers in the array with -1.

#5. Reshape a 1D NumPy array into a 3x3 matrix:

#arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#6. Find the max and min values from this array:


# np.array([12, 56, 98, 3, 45, 77, 29])

In [40]:
#2.Generate a 4x4 matrix of random integers between 1 and 10
ar=np.random.randint(1,100,(4,4))
ar

array([[78, 75, 25,  9],
       [40, 64, 17, 80],
       [70,  9, 30, 68],
       [94, 35, 52, 14]], dtype=int32)

In [41]:
#3. Extract all even numbers from the array:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

even_numbers = arr[arr % 2 == 0]

print(even_numbers)  


[ 2  4  6  8 10]


In [42]:
#4. Replace all odd numbers in the array with -1.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[arr % 2 != 0] = -1

print(arr)  

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [43]:
#5. Reshape a 1D NumPy array into a 3x3 matrix:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
#6. Find the max and min values from this array:np.array([12, 56, 98, 3, 45, 77, 29])
arr=np.array([12, 56, 98, 3, 45, 77, 29])
arr.max()

np.int64(98)

In [45]:
arr =np.ones(10,dtype=int)
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [46]:
arr=np.diag([2,3,4,5,6])
arr

array([[2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [47]:
arr = np.linspace(1,20,10)
arr

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [48]:
# 7,create a 5x5 identities matrix
arr=np.identity(5, dtype=int)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [49]:
#8 sort the array [9,1,7,3,6,2,8,4,5]
arr =np.array([9,1,7,3,6,2,8,4,5])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# 9.Find the sum of all elements in the array [1, 2, 3, 4, 5].
arr=np.array([1, 2, 3, 4, 5])
print(np.sum(arr))

15


In [51]:
# 10. Create a 3×3 NumPy array filled with zeros. **bold text**
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
# Find the most frequently occurring element in an array.
# Given an array, replace all values greater than 10 with 10:
# arr = np.array([5, 15, 25, 10, 8, 3, 12])
# Find the sum of each row in a 384 matrix:
# arr = np.array ( [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] )
# Find the index of the maximum element in the array.
# arr = np.array([10, 20, 5, 30, 25])
# Find the mean, median, and standard deviation of:
# arr - np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Swap column 0 and column 2 in the given 3%3 matrix.
### arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) *bold text*
# Find unique values and their counts in:
# arr = np.array([1, 2, 2, 3, 4, 4, 4, 510])

In [53]:
# 11.Generate a 5x5 matrix where each row contains values from 1 to 5.
arr = np.tile(np.arange(1, 6), (5, 1))
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [54]:
# 12.Find the most frequently occurring element in an array.
arr = np.array([1, 2, 3, 4, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4])
most_frequent = np.bincount(arr).argmax()
print(most_frequent)  


4


In [55]:
# [:,0,2][:2,0]
# swap column 0 and column 2 in the given x matrix
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[:,[0,2]] = arr[:,[2,0]]
arr

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [56]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
# Generate a 5x5 matrix where each row contains values from 1 to 5.


# array creation 3 type 
## arr= np.array([[1,2,3],[4,5,6],[7,8,9]])  
## ar=np.random.randint(1,100,(4,4))
## np.arange


In [58]:
import numpy as np
arr= np.array([[1,2],[4,5]])  
# print(arr[0,[0,1]])
# print(arr+10)
scalar =5
print(arr)


[[1 2]
 [4 5]]


In [59]:
# scaler
# vector
arr= np.array([[1,2],[4,5]])  
arr1= np.array([[1,2],[4,5]]) 
result = arr+arr1
print(result)

[[ 2  4]
 [ 8 10]]


In [60]:
arr= np.array([[1,2,4],[4,5,6]])  
arr1= np.array([1,2,3]) 
# arr11.reshape(3,1)
result = arr+arr1
print(result)


[[2 4 7]
 [5 7 9]]


In [61]:
# tilling method
a=np.array([[1,2],[3,4]]) 
b=np.array([10,20,30]) 
b_tilled=np.tile(b[:2],[2,1])
# print(b_tilled)
a+b_tilled

array([[11, 22],
       [13, 24]])

In [62]:
#1. Add a 1D array [10, 20, 30] to each row of a 2D array. #2d([[1, 2, 3], [4, 5, 6]])

#2. Multiply a column vector with a row vector using broadcasting:
# X= np.array([[1], [2], [3]) # Shape (3,1)
# Ynp.array([10, 20, 30])  #Shape (1,3)

#3. Subtract a row vector from each row of a 2D matrix:
# A = np.array([[5, 10, 15], [20, 25, 30]) # Shape (2,3)
# B np.array([1, 2, 3])    # Shape (3,)

#4. Compute the mean of a 2D array and subtract it from each row.
# A = np.array([[10, 20, 30], [40, 58, 60], [70, 80, 90])

#5. Fix the broadcasting error by reshaping the array.
# Anp.array([[1, 2], [3, 4])
# Bnp.array([10, 20])

#6. Multiply each row of a matrix by a different scalar.
# Anp.array([[1, 2, 3], [4, 5, 6], [7, 8, 9])
# scalars np.array([1, 2, 3])

#7. Normalize a 2D array (subtract mean and divide by std deviation).
# A-np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9])

In [63]:
#2. Multiply a column vector with a row vector using broadcasting:
# X= np.array([[1], [2], [3]) # Shape (3,1)
# Ynp.array([10, 20, 30])  #Shape (1,3)
X= np.array([[1], [2], [3]])
Y=np.array([10, 20, 30])
result=X*Y
print(result)

[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [64]:
#3. Subtract a row vector from each row of a 2D matrix:
# A = np.array([[5, 10, 15], [20, 25, 30]) # Shape (2,3)
# B np.array([1, 2, 3])    # Shape (3,)
A = np.array([[5, 10, 15], [20, 25, 30]])
B = np.array([1, 2, 3])
result=X-Y
print(result)

[[ -9 -19 -29]
 [ -8 -18 -28]
 [ -7 -17 -27]]


In [65]:
#4. Compute the mean of a 2D array and subtract it from each row.
# A = np.array([[10, 20, 30], [40, 58, 60], [70, 80, 90])

A = np.array([[10, 20, 30], [40, 58, 60], [70, 80, 90]])
mean=A.mean()
result=A-mean
print(result)

[[-40.88888889 -30.88888889 -20.88888889]
 [-10.88888889   7.11111111   9.11111111]
 [ 19.11111111  29.11111111  39.11111111]]


In [66]:
#5. Fix the broadcasting error by reshaping the array.
# Anp.array([[1, 2], [3, 4])
# Bnp.array([10, 20])

In [67]:
#6. Multiply each row of a matrix by a different scalar.
A=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
scalars =np.array([1, 2, 3])
result=A*scalar
print(result)


[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [68]:
#7. Normalize a 2D array (subtract mean and divide by std deviation).
A=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M=A.mean()
S=A.std()
mean_sub_result=A-mean
std_div=mean_sub_result/S
print(std_div)

[[-19.32188358 -18.93458525 -18.54728691]
 [-18.15998858 -17.77269024 -17.38539191]
 [-16.99809358 -16.61079524 -16.22349691]]


In [69]:
'''
Q:1 How to Find the Index of Maximum and Minimum Values in a NumPy Array? arr = np.array([10, 25, 2, 67, 89, 45])

How to Replace All Values Greater than a Threshold with a Specific Value? arr = np.array([3, 10, 18, 21, 5, 9])
# Replace all values greater than 10 with 99 
3. How to Find Unique Elements and Their Counts in an Array? arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
4. How to Perform Row-Wise and Column-Wise Operations in NumPy? matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
5. How to Generate a Random Matrix and Normalize It?
    random_matrix = np.random.rand(3, 3)
    use the formula: (x - mean(row)) / std(row)
    normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))
6. How to Find the Euclidean Distance Between Two Vectors?
v1 = np.array([3, 4, 5])
v2 = np.array([1, 1, 1]) distance = np.sqrt(np.sum((v1 - v2) ** 2))
or
distance = np.linalg.norm(v1 - v2)
7. How to Shuffle Rows of a NumPy Array? arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
How to Find the Dot Product and Cross Product of Two Vectors?
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
umpy as np
angles = np.array([0, np.pi/2, np.pi, 3*np.pi/2])
'''
# Q:1 How to Find the Index of Maximum and Minimum Values in a NumPy Array? arr = np.array([10, 25, 2, 67, 89, 45])
arr = np.array([10, 25, 2, 67, 89, 45])
min=np.amin(arr)
max=np.amax(arr)
print(min,max)

2 89


In [70]:
#2. How to Replace All Values Greater than a Threshold with a Specific Value? arr = np.array([3, 10, 18, 21, 5, 9])
# Replace all values greater than 10 with 99 
arr = np.array([3, 10, 18, 21, 5, 9])
arr[arr>10]=99
print(arr)

[ 3 10 99 99  5  9]


In [71]:
# 3. How to Find Unique Elements and Their Counts in an Array? arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
np.unique(arr)

array([1, 2, 3, 4, 5])

In [72]:
# 4. How to Perform Row-Wise and Column-Wise Operations in NumPy? matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix1= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_sum = np.sum(matrix, axis=1)
print(row_sum)  
row_mean = np.mean(matrix, axis=1)
print(row_mean)  



[ 6 15 24]
[2. 5. 8.]


In [73]:
# 5. How to Generate a Random Matrix and Normalize It?
#     random_matrix = np.random.rand(3, 3)
#     use the formula: (x - mean(row)) / std(row)
#     normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))
